### ISSUE TITLE
fix: 요청 값 유효성 검증 추가

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#109]
### 💼 작업 설명

Valid, Validated 어노테이션을 사용하여 입력으로 들어온 값에 대한 유효성 검증 로직 추가합니다.

### ✅ To-do

- [x] 회원가입 시 닉네임 글자 수 제한
- [x] 선물박스 만들 때 글자 수 제한
  - [x] 선물박스 이름
  - [x] 보내는 사람 이름
  - [x] 받는 사람 이름
  - [x] 편지 내용
