### ISSUE TITLE
fix: 서버 드리븐 UI 확정에 따른 박스 이미지 관련 API 수정

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#112]
### 💼 작업 설명

서버 드리븐 UI가 확정되며 박스 이미지 관련 데이터와 네이밍이 변했고, 이를 반영하기 위해 박스 이미지와 관련된 API를 수정합니다.

### ✅ To-do

- [x] 박스 엔티티 필드 수정
- [x] 박스 이미지 조회 API 수정
- [x] 주고받은 박스 조회 API 수정
