### ISSUE TITLE
refactor: 대소문자를 혼용한 URI 변경

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#137]
### 💼 작업 설명

페이징이 적용된 API의 마지막 데이터를 불러오기 위해 사용한 query parameter 이름을 카멜 케이스로 적어 해당 API의 URI에 대소문자가 혼용되어있습니다.
API URI를 소문자로 통일할 수 있도록 카멜 케이스로 된 query parameter 이름을 케밥 케이스로 변경합니다.

### ✅ To-do

- [ ] query parameter 수정
  - [ ] 스티커 조회 API 
  - [ ] 주고받은 선물박스 조회 API
