### ISSUE TITLE
feat: 선물박스 status 변경 API 및 보내지 않은 선물박스 조회 API 구현

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#172]
### 💼 작업 설명

- '나중에 보낼게요' 기능 구현을 위해 선물박스에 status 필드를 추가하고, status 필드를 변경할 수 있는 API를 구현합니다.
- '나중에 보낼게요'를 누른 선물박스를 모아볼 수 있도록 보내지 않은 선물박스 조회 API를 구현합니다.

### ✅ To-do

- [x] GiftBox 엔티티에 status 필드 추가
- [x] GiftBox 엔티티 status 변경 API 구현
- [x] 보내지 않은 선물박스 조회 API 구현
  - [x] 이번 스프린트에서는 페이징 없이 최신순으로 6개만 조회 가능하도록 하고 추후 필요할 경우 페이징을 도입합니다.
- [x] 보낸 선물박스에 status가 DELIVERED인 선물박스만 뜨도록 보낸 선물박스 API 수정
