### ISSUE TITLE
feat: 홈 화면에 띄울 선물박스 조회 API

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#188]
### 💼 작업 설명

패키의 선물박스 플로우에 대한 클라이언트의 의도가 다르게 패키의 선물박스 조회 API를 구현했습니다. 
메인화면에 띄울 선물박스 조회 API를 구현합니다.

### ✅ To-do

- [x] 패키의 선물박스 조회 API 제거
- [x] 홈 화면에 띄울 선물박스 조회 API 추가
  - [x] 홈 화면에 띄울 선물박스가 없는 경우에 대한 클라이언트 단 테스트를 위해 랜덤하게 빈 JSON 객체를 반환
- [x] 선물박스가 최초 1회만 조회되도록 로직 개선
  - [x] 확인한 선물박스일 경우 빈 JSON 객체 반환
- [x] _기능 개발 이전에 다운받은 사람들이 온보딩 선물박스를 받을 수 있도록 flyway 스크립트 추가_ → 기능 개발 이전에 다운받은 사람이 제한되어 있고, 추후 변경될 가능성이 없으므로 Datagrip에서 직접 쿼리를 쏘는 것으로 대체하였습니다.
