### ISSUE TITLE
feature: Server Driven UI 관련 조회 API 구현

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#32]
### 💼 작업 설명

Server Driven UI를 위해 서버 단에 저장된 UI 이미지를 조회하는 API를 구현합니다.

### ✅ To-do

- [x] 프로필 조회
- [x] 박스 디자인 조회
- [x] 편지 봉투 디자인 조회
- [x] 패키 추천 음악 조회
