### ISSUE TITLE
feat: 공통 응답 포맷 제작

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#5]
### 💼 작업 설명

API Response를 통일성 있게 관리하기 위해 공통 응답 포맷을 제작합니다.

### ✅ To-do

- [ ] 공통 Response 객체 생성
- [ ] 공통 Exception 처리
- [ ] 에러 코드 Spring Rest Docs로 문서화
