### ISSUE TITLE
fix: Server Driven UI 관련 API에 sequence 기준 정렬 조건 추가

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#68]
### 💼 작업 설명

Server Driven UI 관련 API에 sequence 컬럼을 추가했지만 정렬 조건을 추가하지 않아 id순(DB에 삽입된 순)으로 반환하고 있습니다.
순서에 맞게 데이터를 반환하도록 정렬 조건을 추가합니다.

### ✅ To-do

- [x] 패키 추천 음악 조회 API sequence 컬럼 추가 및 정렬
- [x] 스티커 조회 API 정렬 조건 추가
- [x] 프로필 이미지 조회 API 정렬 조건 추가
- [x] 편지 봉투 디자인 조회 API 정렬 조건 추가
- [x] 박스 디자인 조회 API 정렬 조건 추가

**Comment by leeeeeyeon** [comment]
테스트용 더미 데이터가 중복되어 삽입되는 문제 발생
Reference: https://ksh-coding.tistory.com/99
