### ISSUE TITLE
feat: Spring Security, JWT 관련 설정 추가

### ISSUE THREAD

**Issue by leeeeeyeon** [Central-MakeUs/Packy-Server#69]
### 💼 작업 설명

기존에 꼼꼼하지 않았던 보안을 강화하기 위해 Spring Security와 JWT 설정을 고도화합니다.
더불어, 간단한 API 테스트에 사용할 수 있는 test 타입 회원가입을 추가합니다.

### ✅ To-do

- [x] SecurityConfig whitelist 작성
- [x] 회원가입 API에 test 타입 추가
- [x] 만료된 JWT에 대한 예외처리 추가
